<?xml version="1.0"?>
<robot name="rb1_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rb1_base_v3" params="publish_bf hq">

  <!-- Robot mechanical and motor parameters -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_width" value="0.175" />

  <!-- BASE FOOTPRINT -->
  <xacro:if value="${publish_bf}">
    <link name="base_footprint">
      <!--visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <box size="0.001 0.001 0.001" />
          </geometry>
      </visual-->
    </link>

    <joint name="base_footprint_joint" type="fixed">
       <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="base_link" />
    </joint>
  </xacro:if>

  <!-- BASE_LINK -->
  <link name="base_link">
    <inertial>
      <mass value="25.0" />
      <origin xyz="0 0 0.07" />
      <inertia  ixx="0.605" ixy="0.0"  ixz="0.0"  iyy="0.5435"  iyz="0.0"  izz="0.981" />
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <xacro:if value="${hq}">
       <geometry>
	     <mesh filename="package://rb1_base_description/meshes/bases/rb1_base_v3.stl"/>
       </geometry>
       </xacro:if>
       <xacro:unless value="${hq}">
       <geometry>
       <mesh filename="package://rb1_base_description/meshes/bases/rb1_base_v3.stl"/>
       </geometry>
       </xacro:unless>
       <material name="darkgrey">
         <color rgba="0.1 0.1 0.1 1"/>
       </material>
    </visual>
    <!--collision>
       <origin xyz="0 0 0" rpy="0 0 0 " />
       <geometry>
         <mesh filename="package://rb1_base_description/meshes/bases/rb1_base_v3.dae"/>
       </geometry>
    </collision-->
  </link>

  <joint name="front_cover_joint" type="fixed">
     <origin xyz="0.220 0.0 0.004" rpy="0 0 0 " />
     <parent link="base_link"/>
     <child link="front_cover_link" />
  </joint>

  <!-- FRONT COVER -->
  <link name="front_cover_link">
    <inertial>
      <mass value="0.25" />
      <origin xyz="0 0 0.05" />
      <inertia  ixx="0.001" ixy="0.0"  ixz="0.0"  iyy="0.001"  iyz="0.0"  izz="0.001" />
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <xacro:if value="${hq}">
       <geometry>
	     <mesh filename="package://rb1_base_description/meshes/bases/rb1_front_cover_v3.stl"/>
       </geometry>
       </xacro:if>
       <xacro:unless value="${hq}">
       <geometry>
       <mesh filename="package://rb1_base_description/meshes/bases/rb1_front_cover_v3.stl"/>
       </geometry>
       </xacro:unless>
       <material name="black">
         <color rgba="0.0 0.0 0.0 1"/>
       </material>
    </visual>
    <collision>
       <origin xyz="0 0 0" rpy="0 0 0 " />
       <geometry>
         <mesh filename="package://rb1_base_description/meshes/bases/rb1_front_cover_v3.dae"/>
       </geometry>
    </collision>
  </link>

  <joint name="top_covert_joint" type="fixed">
     <origin xyz="0.0 0.0 0.243" rpy="0 0 0 " />
     <parent link="base_footprint"/>
     <child link="top_cover_link" />
  </joint>

  <!-- FRONT COVER -->
  <link name="top_cover_link">
    <inertial>
      <mass value="0.25" />
      <origin xyz="0 0 0" />
      <inertia  ixx="0.0007" ixy="0.0"  ixz="0.0"  iyy="0.0007"  iyz="0.0"  izz="0.001" />
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <xacro:if value="${hq}">
		   <geometry>
			 <mesh filename="package://rb1_base_description/meshes/bases/rb1_top_cover_v3.stl"/>
		   </geometry>
       </xacro:if>
       <xacro:unless value="${hq}">
		   <geometry>
		   <mesh filename="package://rb1_base_description/meshes/bases/rb1_top_cover_v3.stl"/>
		   </geometry>
       </xacro:unless>
       <material name="black">
         <color rgba="0.0 0.0 0.0 1"/>
       </material>
    </visual>
    <collision>
       <origin xyz="0 0 0" rpy="0 0 0 " />
       <geometry>
         <mesh filename="package://rb1_base_description/meshes/bases/rb1_top_cover_v3.dae"/>
       </geometry>
    </collision>
  </link>


  <!-- DOCKING CONTACTS -->
  <joint name="base_docking_joint" type="fixed">
     <origin xyz="0.030 0.000 0.068" rpy="0 0 0 " />
     <parent link="front_cover_link"/>
     <child link="base_docking_contact_link" />
  </joint>

  <!-- DOCKING LINK -->
  <link name="base_docking_contact_link" />


  </xacro:macro>
</robot>
